### ISSUE TITLE
Add Spell SRD Data

### ISSUE THREAD

**Issue by Freyj** [Freyj/Fluffy-Hero-Maker#2]
- Keep a structure of srd_lvl_[number].json for files 

- [x] Cantrips
- [x] Lvl 1 spells
- [x] Lvl 2 spells
- [x] Lvl 3 spells
- [x] Lvl 4 spells
- [x] Lvl 5 spells
- [x] Lvl 6 spells
- [x] Lvl 7 spells
- [x] Lvl 8 spells
- [x] Lvl 9 spells

**Comment by Freyj** [comment]
currently doing the lvl2 spells file

**Comment by Freyj** [comment]
Working on the level 3 spells

**Comment by viACHIZv** [comment]
Hi @Freyj , I can get this done by taking the data from https://open5e.com/ and formatting it based on your template in utils. Would you like me to?

**Comment by Freyj** [comment]
Yes, thank you, sorry I didn't answer before :+1:
